defaults: &defaults
  base_url: "https://komin.malmo.se/"
  assets_url_base: "//assets.malmo.se/internal/v4-staging/"
  stub_auth: false
  pre_generated_reports:
    - id: 1
      desc: 'Aktuella ärenden: Alla barn som inte är utskrivna'
      filename: 'aktuella_arenden.xlsx'
    - id: 2
      desc: 'Aktuellt år: Barn som varit inskrivna i år eller har en placering första januari detta år'
      filename: 'aktuellt_ar.xlsx'

development: &development
  <<: *defaults
  assets_url_base: "//assets.malmo.se/internal/v4/"
  cache_ttl: 1
  max_age: 0
  title_suffix: "MEKS (utveckling)"
  stub_auth: true

local_test:
  <<: *development

test:
  <<: *defaults
  assets_url_base: "//assets.malmo.se/internal/v4-staging/"
  cache_ttl: 43200
  max_age: 14400
  title_suffix: "MEKS (test)"

production: &production
  <<: *defaults
  assets_url_base: "//assets.malmo.se/internal/v4/"
  cache_ttl: 43200
  max_age: 14400
  title_suffix: "MEKS"

staging:
  <<: *production
  title_suffix: "MEKS (staging)"
  assets_url_base: "//assets.malmo.se/internal/v4-staging/"
