defaults: &defaults
  base_url: "https://komin.malmo.se/"
  assets_url_base: "//assets.malmo.se/internal/v4-staging/"
  auth_method: ldap # saml ldap or stub
  pre_generated_reports:
    - id: 1
      desc: 'Aktuella ärenden: Alla barn som inte är utskrivna'
      filename: 'aktuella_arenden.xlsx'
    - id: 2
      desc: 'Aktuellt år: Barn som varit inskrivna i år eller har en placering första januari detta år'
      filename: 'aktuellt_ar.xlsx'
    - id: 3
      desc: 'Placeringar aktuellt kvartal'
      filename: 'placeringar_aktuellt_kvartal.xlsx'
    - id: 4
      desc: 'Alla placeringar'
      filename: 'alla_placeringar.xlsx'

development: &development
  <<: *defaults
  assets_url_base: "//assets.malmo.se/internal/v4/"
  cache_ttl: 1
  max_age: 0
  title_suffix: "MEKS (utveckling)"
  auth_method: stub

local_test:
  <<: *development
  auth_method: stub

test:
  <<: *defaults
  assets_url_base: "//assets.malmo.se/internal/v4-staging/"
  cache_ttl: 43200
  max_age: 14400
  title_suffix: "MEKS (test)"
  auth_method: ldap

production: &production
  <<: *defaults
  assets_url_base: "//assets.malmo.se/internal/v4/"
  cache_ttl: 43200
  max_age: 14400
  title_suffix: "MEKS"
  auth_method: ldap

staging:
  <<: *production
  title_suffix: "MEKS (staging)"
  assets_url_base: "//assets.malmo.se/internal/v4-staging/"
  auth_method: ldap
