analysis:
  analyzer:
    name_index:
      tokenizer: edge_ngram_2
      char_filter:
      - hyphen
      filter:
      - lowercase
    name_search:
      tokenizer: standard
      filter:
      - lowercase
      char_filter:
      - hyphen
    nmbr:
      tokenizer: keyword
      filter:
      - nmbr

  tokenizer:
    edge_ngram_2:
      type: edgeNGram
      min_gram: 2
      max_gram: 50
      token_chars:
      - letter

  filter:
    nmbr:
      type: edgeNGram
      min_gram: 2
      max_gram: 20

  char_filter:
    hyphen_space:
      type: pattern_replace
      pattern: "[-,\\s]"
      replacement: ''
    hyphen:
      type: pattern_replace
      pattern: "[-]"
      replacement: ''
